### ISSUE TITLE
Links to admin pages assume TeamCity is installed to root URL

### ISSUE THREAD

**Issue by bluepixelmike** [IIIEII/ServerConfigurations#1]
I have a TeamCity server installed installed to a sub-path and the links to create a configuration point to the correct location. For example, my TeamCity server instance is running at http://builds/teamcity/, instead of http://builds/. The links use /admin when they should be /teamcity/admin or a relative path.

When clicking the link, I'm taken to:
http://builds/admin/admin.html?item=ServerConfigurations&action=new
instead of:
 http://builds/**teamcity**/admin/admin.html?item=ServerConfigurations&action=new

**Comment by IIIEII** [comment]
Could you tell me your way to make Teamcity work in sub-path? I tried some configurations without success. I need it to test patch.

**Comment by bluepixelmike** [comment]
Thanks for the quick fix. I'd hate to re-open this, but there's an issue with template links now. Clicking on "Create new template" take me to the URL:
/teamcity/admin/**admin**/admin.html?item=ServerConfigurations&action=newTemplate
There's an extra admin in the path.

**Comment by IIIEII** [comment]
Somehow I put wrong zip-file to my bin folder.
Thank's for your help in finding such a foolish mistake.

**Comment by bluepixelmike** [comment]
Awesome, it works perfect now! Thanks a lot.
