### ISSUE TITLE
Plugin doens't work with TeamCity 9.1.3

### ISSUE THREAD

**Issue by sharov** [IIIEII/ServerConfigurations#2]
I've installed plugin, but link to plugin admin page isn't available. What do I need to do?

![2015-09-24 11 11 55](https://cloud.githubusercontent.com/assets/30379/10068490/70c8573c-62ad-11e5-8349-e5953fb5c0d0.png)

**Comment by IIIEII** [comment]
Do you have system administrator role? Did you try to restart teamcity?

**Comment by sharov** [comment]
Yes. It's already restarted.

**Comment by IIIEII** [comment]
OK, what about system administrator role?
And what version of teamcity do you have?

**Comment by sharov** [comment]
Yes, I have system administrator role.
TeamCity 9.1.3

**Comment by IIIEII** [comment]
Of course, version number is in the name of issue...

Anyway, I just upgraded my teamcity to 9.1.3 and it still works as expected.
Let's just check if you have files in places:
%TEAMCITY_DATA_PATH%\plugins.unpacked\ServerConfigurations\server\ServerConfigurations-common.jar
%TEAMCITY_DATA_PATH%\plugins.unpacked\ServerConfigurations\server\ServerConfigurations-server.jar
where %TEAMCITY_DATA_PATH% is folder where teamcity has it's configuration (for example c:\ProgramData\JetBrains\Teamcity or c:\Users\username.BuildServer for windows or ~.BuildServer for linux)

And could you please check your teamcity-server.log file for some errors?

**Comment by wesley-moore-rockalltech** [comment]
Hey IIEII, I've found the same problem on TC 9.0.2 (build 32195). I've uploaded the binary ServerConfigurations.zip via TC GUI and rebooted. It's shown in the list, but the new option hasn't appeared in the Admin page (yes, I'm admin user).

I checked the .unpacked folder and can see both JARs there. (owned by root : -rw-r--r--).

When looking over the teamcity-server.log I found some potential issues:

"nested exception is java.lang.UnsupportedClassVersionError: ServerConfigurations/server/ServerListener : Unsupported major.minor version 51.0;"

Grep'd log:

http://pastie.org/private/ym9yyvw6yz89alvwhyfda

Any help would be greatly appreciated, dying to try this fantastic plugin!

**Comment by IIIEII** [comment]
Hi @wesley-moore-rockalltech!
Looks like you have older java version than I used to compile my plugin. Do you have ability to upgrade it to latest version? Last version of Teamcity uses Java 8.

**Comment by wesley-moore-rockalltech** [comment]
Woah, very fast reply, thanks! At the moment we're running 1.6.0_20 but I will ask the head of IT about this, he's due back in a few minutes. Hopefully we'll get it updated by COB today!

**Comment by IIIEII** [comment]
OK. Let me know then.
Anyway I just uploaded new version of plugin. In addition to previous functionality it could use different server configurations for different branches in VCS.

**Comment by wesley-moore-rockalltech** [comment]
Hi IIIEII, it seems like TC 9.0.2 requires JDK 7 and sadly, we won't be able to upgrade for now due to this restriction. Many thanks for your great support, I hope to use this in future at some point!

**Comment by IIIEII** [comment]
No problem, I recompiled plugin with java 7 and put separate zip file to bin folder. Take a look.

**Comment by wesley-moore-rockalltech** [comment]
Jeez, that's fantastic! I can't thank you enough. Our head of IT is leaving for annual leave for 2 weeks, so we can't risk making any changes until he returns sadly (although I've all the faith in the world it's working perfect :P ). Looking forward to giving this a spin, seems like a real time-saver!

**Comment by wesley-moore-rockalltech** [comment]
Hi again, just thought I'd follow up on the current status. I got to make another attempt at installing/rebooting, but the plugin configuration still doesn't display under Administration. The JRE is still version 1.6.0_20 but I can try upgrading once we've a complete backup of the current TC server (couple days away). Would it be at all possible to try compiling for JRE6 in the mean time? I can try testing it in the evening time. Thanks a lot for all your help!

**Comment by IIIEII** [comment]
Hi! I unexpectedly found jdk1.6 on my mac so I could compile it :)
Now you can find it in bin folder.

**Comment by wesley-moore-rockalltech** [comment]
Hey IIIEII, I'm delighted to say, your plugin works! :+1: 
Thanks so much for your effort, it must be the most compatible plugin for TC now! lol
It seems like it will save loads of time in configuring new deployments, can't wait to get started!
**Confirmed working on : 9.0.2 (build 32195) - JRE 1.6.0_20**

**Comment by IIIEII** [comment]
Glad to hear that! Let me know if you'll need some new features.
